config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
	resources :car_items
  resources :cars
  resources :equipments
  resources :grades
  resources :makers
  root "cars#link"
  get "/enquiries/insurance", to: "enquiries#insurance"
  post  "/enquiries/create", to: "enquiries#create" , as: 'enquiries'
  get "/enquiries/automobile", to: "enquiries#automobile"
  get "/enquiries/repair", to: "enquiries#repair"
  get "/enquiries/assessment", to: "enquiries#assessment"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
has_many :grades
has_many :car_items
belongs_to :maker



end

app/models/car_item.rb
class CarItem < ApplicationRecord
belongs_to :maker
belongs_to :car
belongs_to :grade
has_many :equipments
accepts_nested_attributes_for :equipments, allow_destroy: true
attachment :image
enum caryear:["1990年 平成2年","1991年 平成3年","1992年 平成4年","1993年 平成5年","1994年 平成6年","1995年 平成7年","1996年	 平成8年",
					"1997年	平成9年","1998年	平成10年","1999年 平成11年","2000年 平成12年","2001年 平成13年","2002年 平成14年	","2003年 平成15年",
					"2004年	平成16年","2005年	 平成17年","2006年 平成18年","2007年 平成19年","2008年	平成20年","2009年	 平成21年","2010年 平成22年",
					"2011年	平成23年","2012年 平成24年","2013年 平成25年","2014年 平成26年","2015年	平成27年","2016年	 平成28年","2017年 平成29年",
					"2018年	平成30年","2019年 令和元年(平成31年)"]


end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
belongs_to :user
enum areas: ["北海道","青森県","岩手県","宮城県","秋田県","山形県","福島県",
			"茨城県","栃木県","群馬県","埼玉県","千葉県","東京都","神奈川県",
			"新潟県","富山県","石川県","福井県","山梨県","長野県","岐阜県",
			"静岡県","愛知県","三重県","滋賀県","京都府","大阪府","兵庫県",
			"奈良県","和歌山県","鳥取県","島根県","岡山県","広島県","山口県",
			"徳島県","香川県","愛媛県","高知県","福岡県","佐賀県","長崎県",
			"熊本県","大分県","宮崎県","鹿児島県","沖縄県"]

enum insurance_selects:["保険に加入したい", "保険の見直し", "その他"]

enum mycar_makers:["レクサス","トヨタ","日産","ホンダ","三菱","マツダ","スバル",
				"スズキ","ダイハツ","TVR","アストンマーティン","ジャガー","ロールスロイス","ランドローバー",
				"ベントレー","ロータス","MG","ローバー","キャデラック","シボレー","ハマー",
				"クライスラー","フォード","サターン","BMW","アウディ","ポルシェ","メルセデス・ベンツ",
				"フォルクスワーゲン","オペル","マイバッハ","シトロエン","プジョー","ルノー","ブガッティ",
				"フェラーリ","フィアット","アルファロメオ","マセラティ","ランボルギーニ","アウトビアンキ","ランチア",
				"アバルト","サーブ","ボルボ"]

enum mycar_years:["1990年 平成2年","1991年 平成3年","1992年 平成4年","1993年 平成5年","1994年 平成6年","1995年 平成7年","1996年	 平成8年",
				"1997年	平成9年","1998年	平成10年","1999年 平成11年","2000年 平成12年","2001年 平成13年","2002年 平成14年	","2003年 平成15年",
				"2004年	平成16年","2005年	 平成17年","2006年 平成18年","2007年 平成19年","2008年	平成20年","2009年	 平成21年","2010年 平成22年",
				"2011年	平成23年","2012年 平成24年","2013年 平成25年","2014年 平成26年","2015年	平成27年","2016年	 平成28年","2017年 平成29年",
				"2018年	平成30年","2019年 令和元年(平成31年)"]

enum mycar_distances:["不明","~5000km","10001km~15000km","15001km~20000km","20001km~25000km","25001km~30000km","30001km~35000km",
					"35001km~40000km","40001km~45000km","45001km~50000km","50001km~55000km","55001km~60000km","60001km~65000km",
					"65001km~70000km","70001km~75000km","75001km~80000km","80001km~85000km","85001km~90000km","90001km~95000km",
					"95001km~100000km","100000km以上"]

enum numbers:["査定", "在庫確認", "車検", "保険", "修理"]
end

app/models/equipment.rb
class Equipment < ApplicationRecord
belongs_to :car_item



end

app/models/grade.rb
class Grade < ApplicationRecord
belongs_to :car
has_many :car_items

enum  shift:[:"AT",:"MT"]
end

app/models/maker.rb
class Maker < ApplicationRecord
has_many :cars
has_many :car_items


end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :enquiry

	validates :name_first, presence: true
	validates :name_last, presence: true
	validates :post_code, presence: true
	validates :phone, presence: true
	validates :address, presence: true
end

app/controllers/car_items_controller.rb
class CarItemsController < ApplicationController
def new
    @car_item = CarItem.new
end

def create
    @car_item = CarItem.new(car_item_params)
    @car_item.save
     #binding.pry
    redirect_to cars_path
end

def index
 	@maker = Maker.find(params[:id])
 	@user = current_user
end

def show
	@car_item = CarItem.find(params[:id])
	@eqipment = Equipment.find(params[:id])
	@enquiry = Enquiry.new
	@user = current_user
end


def car_item_params
    params.require(:car_item).permit(:id,
									:year,
									:distance,
									:inspection,
									:color,
									:price,
									:image,
									:grade_id,
									:car_id,
									:maker_id,
									:user_id,
									equipments_attributes: [:id,
															:name,
					    									:grade_id,
					    									:_destroy,])
end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

def new
    @car = Car.new
       disc = @car.grades.build
       disc.car_items.build
end

def create
    @car = Car.new(car_params)
    @car.save
     #binding.pry
    redirect_to cars_path
end

def index
 	@makers = Maker.all
 	#binding.pry
end

def link

end

def car_params
    params.require(:car).permit(:id,
    							:name,
    							:maker_id,
    							grades_attributes: [:id,
    												:name,
    												:displacement,
				    								:fixed_number,
				    								:car_id,
				    								:shift,
				    								car_items_attributes: [:id,
				    														:year,
									    									:distance,
									    									:inspection,
									    									:color,
									    									:price,
									    									:image_id,
									    									:grade_id],
									    			equipments_attributes: [:id,
									    									:name,
									    									:grade_id,
									    									:_destroy,]])
end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_items_helper.rb
module CarItemsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/enquirys_helper.rb
module EnquirysHelper
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/car_items/_equipment_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <span>装備名</span>
  	<span><%= link_to_remove_association "装備を削除", f  %></span>
    <%= f.text_field :name, class: "form-control", placeholder: '装備名を入力してください' %>
  </div>
</div>

app/views/car_items/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div>
              <ul>
                <p>車一覧</p>
                <div class="col-md-3">
                  <li></li>
                </div>
                <div class="col-md-8">
                  <div class="col-md-3">
                    <li>金額</li>
                  </div>
                  <div class="col-md-3">
                    <li>年式</li>
                  </div>
                  <div class="col-md-2">
                    <li>走行距離</li>
                  </div>
                  <div class="col-md-2">
                    <li>排気量</li>
                  </div>
                  <div class="col-md-2">
                    <li>車検</li>
                  </div>
              </ul>
            </div>
              <% @maker.cars.each do |car| %>
                  <% car.grades.each do |grade| %>
                      <% grade.car_items.each do |item| %>
                        <%= link_to car_item_path(item) do %>
                          <ul>
                            <div class="col-md-12" >
                              <li><%= @maker.name %><%= car.name %><%= grade.name %></li>
                            </div>
                            <div class="col-md-3">
                              <li><%= attachment_image_tag item, :image, fallback: "no_image.jpg", size:'230x150', format:'jpg' %>
                              </li>
                            </div>
                            <div class="col-md-8">
                              <div class="col-md-3">
                                <li><%= item.price %>万円</li>
                              </div>
                              <div class="col-md-3">
                                <li><%= item.year %></li>
                              </div>
                              <div class="col-md-2">
                                <li><%= item.distance %>km</li>
                              </div>
                              <div class="col-md-2">
                                <li><%= grade.displacement %>cc</li>
                              </div>
                              <div class="col-md-2">
                                <li><%= item.inspection %></li>
                              </div>
                              <div class="col-md-11">
                                <p>装備⬇︎</p>
                                  <% item.equipments.each do |equipment| %>
                                     <%= equipment.name %>/
                                  <% end %>
                                  <% end %>
                              </div>
                            </ul>
                      <% end %>
                  <% end %>
              <% end %>
        </div>
    </div>
</div>

app/views/car_items/new.html.erb
<div class="container" style="margin-top:8em;">
    <div class="row">
        <div class="col-md-6 col-md-offset-3" >
            <%= form_for(@car_item) do |f| %>
                <ul>
                    <li>
                        メーカー
                        <p><%= f.select :maker_id, Maker.all.map{|t| [t.name, t.id]}, :prompt => "選択してください" %></p>
                    </li>
                    <li>
                        車名
                        <p><%= f.select :car_id, Car.all.map{|n| [n.name, n.id]}, :prompt => "選択してください" %></p>
                    </li>
                    <li>
                        グレード
                        <p><%= f.select :grade_id, Grade.all.map{|y| [y.name, y.id]}, :prompt => "選択してください" %></p>
                    </li>
                            <li>
								年式
								<p><%= f.select :year, CarItem.caryears.keys.to_a,{} , {prompt: '選択してください'} %></p>
							</li>
							<li>
								車検
								<p><%= f.text_field :inspection, class: "form-control", placeholder: '車検を入力してください{**年**月}' %></p>
							</li>
                            <li>
                                価格
                                <p><%= f.text_field :price, class: "form-control", placeholder: '価格を入力してください' %>万円</p>
                            </li>
                            <li>
                                距離
                                <p><%= f.text_field :distance, class: "form-control", placeholder: '走行距離を入力してください' %>km</p>
                            </li>
                            <li>
                                ジャケット写真
                                <p><%= f.attachment_field :image %></p>
                            </li>
                            <li>
                                色
                                <p><%= f.text_field :color, class: "form-control", placeholder: '色を入力してください' %></p>
                            </li>
                            <li>
								<div id="equipments">
									<%= f.fields_for :equipments do |equipment| %>
									<%= render 'equipment_fields', t: equipment  %>
									<% end %>
								</div>
								<div class="links">
								<span><%= link_to_add_association '装備を追加', f, :equipments %></span>
								</div>
							</li>
                </ul>
                <%= f.submit class: "btn-flat-border" %>
            <% end %>
        </div>
    </div>
</div>

app/views/car_items/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <ul>
              <div class="col-md-12" >
                <li><%= @car_item.maker.name %><%= @car_item.car.name %><%= @car_item.grade.name %></li>
              </div>
              <div class="col-md-5" >
                <li><%= attachment_image_tag @car_item, :image, fallback: "no_image.jpg", size:'400x350', format:'jpg' %>
                </li>
              </div>
              <div class="col-md-7" >
                <div class="col-md-3" >
                  <li>シフト</li>
                  <li>色</li>
                  <li>車検</li>
                </div>
                <div class="col-md-3" >
                  <li><%= @car_item.grade.shift %></li>
                  <li><%= @car_item.color %></li>
                  <li><%= @car_item.inspection %></li>
                </div>
                <div class="col-md-3" >
                  <li>定員</li>
                  <th>排気量</li>
                  <li>走行距離</li>
                </div>
                <div class="col-md-3" >
                  <li><%= @car_item.grade.fixed_number %></li>
                  <li><%= @car_item.grade.displacement %>cc</li>
                  <li><%= @car_item.distance %></li>
                </div>
                <div class="col-md-10" >
                  <p>装備⬇︎</p>
                    <% @car_item.equipments.each do |equipment| %>
                       <%= equipment.name %>/
                    <% end %>
                </div>
            </ul>
        </div>
    </div>
</div>
<div class="text-center" >
  <h1>今すぐお問い合わせ！</h1>
    <%= form_for(@enquiry) do |f| %>
    <%= f.hidden_field :number, :value => "在庫確認" %>
    <h3>名前</h3>
      <%= @user.name_last %>
      <%= @user.name_first %>
    <h3>電話番号</h3>
      <%= @user.phone %>
    <h3>地域</h3>
      <%= f.select :area, Enquiry.areas.keys.to_a,{} %>
    <h3>メールアドレス</h3>
      <%= @user.email %>
    <h4><%= link_to "ユーザー情報変更", edit_user_path %></h4>
    <div class="actions">
      <%= f.submit '在庫確認・お問合せ(無料)' %>
    </div>
    <% end %>
</div>